CREATE DATABASE APP_BIBLIOTECA;
USE APP_BIBLIOTECA;

CREATE TABLE LOGIN(
	USUÁRIO VARCHAR(20),
	SENHA VARCHAR(20)
);


CREATE TABLE LIVROS(
	TÍTULO VARCHAR(100),
	AUTOR VARCHAR(50),
	EDITORA VARCHAR(50),
	ANO_PUBLICAÇÃO INT(4),
	EDIÇÃO INT(1),
	IDIOMA VARCHAR(20),
	ANO_COMPRA INT(4),
	VOLUME INT(1),
	PREÇO FLOAT(10.2),
	PAGINAS INT(5),
	ESTADO CHAR(2)
);

